name: AutoWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up the environment (example for Python, change to suit your project)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  #
